on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # build and publish in parallel:
        include:
          # - goos: aix
          #   goarch: ppc64
          # - goos: android
          #   goarch: "386"
          - goos: android
            goarch: amd64
          # - goos: android
          #   goarch: arm
          - goos: android
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: dragonfly
            goarch: amd64
          - goos: freebsd
            goarch: "386"
          - goos: freebsd
            goarch: amd64
          - goos: freebsd
            goarch: arm
          - goos: freebsd
            goarch: arm64
          - goos: freebsd
            goarch: riscv64
          # - goos: illumos
          #   goarch: amd64
          # - goos: ios
          #   goarch: amd64
          # - goos: ios
          #   goarch: arm64
          # - goos: js
          #   goarch: wasm
          - goos: linux
            goarch: "386"
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: loong64
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: ppc64
          - goos: linux
            goarch: ppc64le
          - goos: linux
            goarch: riscv64
          - goos: linux
            goarch: s390x
          - goos: netbsd
            goarch: "386"
          - goos: netbsd
            goarch: amd64
          - goos: netbsd
            goarch: arm
          - goos: netbsd
            goarch: arm64
          - goos: openbsd
            goarch: "386"
          - goos: openbsd
            goarch: amd64
          - goos: openbsd
            goarch: arm
          - goos: openbsd
            goarch: arm64
          - goos: openbsd
            goarch: mips64
          # - goos: plan9
          #   goarch: "386"
          # - goos: plan9
          #   goarch: amd64
          # - goos: plan9
          #   goarch: arm
          # - goos: solaris
          #   goarch: amd64
          - goos: windows
            goarch: "386"
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64
    steps:
    - name: OS name
      echo "OS_NAME=${{ matrix.goos }}" >> $GITHUB_ENV
      if: matrix.goos == 'darwin'
      run: echo "OS_NAME=macOS" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        asset_name: timezilla-${{ env.OS_NAME }}-${{ matrix.goarch }}
